export type ResourceType = 
  | 'TRIANGLE'
  | 'SQUARE'
  | 'CIRCLE'
  | 'MATERIALS'
  | 'INDUSTRIALS'
  | 'CONSUMER_DISCRETIONARY'
  | 'CONSUMER_STAPLES'
  | 'CONSUMER_CYCLICAL'
  | 'CONSUMER_DEFENSIVE'
  | 'ENERGY'
  | 'HEALTHCARE'
  | 'TECHNOLOGY'
  | 'GENERAL'; 