remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
sidebar:
  - name: "Rules Overview"
    url: "#rules-overview"
  - name: "End Game Condition"
    url: "#end-game-condition"
  - name: "Game Flow"
    url: "#game-flow"
  - name: "Players"
    url: "#players"
  - name: "Stock Rounds"
    url: "#stock-rounds"
  - name: "Operating Rounds"
    url: "#operating-rounds"
  - name: "Investor Tranches"
    url: "#investor-tranches"
  - name: "Insolvency and Bankruptcy"
    url: "#insolvency-and-bankruptcy"
  - name: "Prestige Tokens"
    url: "#prestige-tokens"
  - name: "Customer Movement"
    url: "#customer-movement"
  - name: "Companies"
    url: "#companies"
  - name: "End Turn Events"
    url: "#end-turn-events"
  - name: "Game Phases"
    url: "#game-phases"
